java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Tremblay' for key 'shop.UK_ksa05ndh95n2bfdwb5wt68541'
java.lang.NullPointerException: Cannot invoke "exam.model.Shop.getName()" because the return value of "exam.model.Laptop.getShop()" is null